core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import IndexView, CadastroView, CategoriaView, ProdutoView, CompraView, UserComprasView, UpdateUserView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('cadastro/', CadastroView.as_view(), name='cadastro'),
    path('update_user/', UpdateUserView.as_view(), name='update_user'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('categoria/<slug:slug>/', CategoriaView.as_view(), name='categoria'),
    path('<slug:slug>/', ProdutoView.as_view(), name='produto'),
    path('<slug:slug>/comprar/', CompraView.as_view(), name='comprar'),
    path('<pk>/user/compras/', UserComprasView.as_view(), name='user_compras'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.dispatch import receiver

from django.utils.safestring import mark_safe
from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField

class Categoria(models.Model):
    class Meta:
        ordering = ('nome', )

    nome = models.CharField(u'Nome', max_length=120, help_text=u'Informe o nome do produto.')
    slug = models.SlugField(u'URL', unique=True, max_length=120, blank=True)

    def get_absolute_url(self):
        return reverse('categoria', kwargs={'slug': self.slug})

    def __str__(self):
        return self.nome

@receiver(pre_save, sender=Categoria)
def categoria_slug_pre_save(sender, instance, raw, using, update_fields, **kwargs):
    if not instance.slug:
        new_slug = slugify(instance.nome)
        instance.slug = new_slug
        num = 1
        while Categoria.objects.filter(slug=instance.slug).exists():
            instance.slug = u'%s-%s' % (new_slug, num)
            num += 1

class Produto(models.Model):
    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ('valor', )

    STATUS_CHOICES = (
        ('P', u'Publicado'),
        ('R', u'Rascunho'),
    )

    nome = models.CharField(u'Nome', max_length=120, help_text=u'Informe o nome do produto.')
    slug = models.SlugField(u'URL', unique=True, max_length=120, blank=True)
    status = models.CharField(u'Status', max_length=1, choices=STATUS_CHOICES)
    data_criacao = models.DateTimeField(u'Criado em', auto_now_add=True)
    data_atualizacao = models.DateTimeField(u'Ultima Atualização', auto_now=True)
    valor = models.DecimalField(u'Valor', max_digits=10, decimal_places=2)
    descricao = RichTextUploadingField(u'Descrição', blank=True)
    imagem = models.ImageField(u'Imagem', upload_to='produtos')
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    autor = models.ForeignKey(User, blank=True, on_delete=models.PROTECT)
    quantidade = models.PositiveIntegerField(u'Quantidade', default=0)

    def get_absolute_url(self):
        return reverse('produto', kwargs={'slug': self.slug})

    def __str__(self):
        return self.nome

@receiver(pre_save, sender=Produto)
def produto_slug_pre_save(sender, instance, raw, using, update_fields, **kwargs):
    if not instance.slug:
        new_slug = slugify(instance.nome)
        instance.slug = new_slug
        num = 1
        while Produto.objects.filter(slug=instance.slug).exists():
            instance.slug = u'%s-%s' % (new_slug, num)
            num += 1

@receiver(post_delete, sender=Produto)
def produto_imagem_post_delete(sender, instance, *args, **kwargs):
    try: instance.imagem.delete()
    except: pass

class Venda(models.Model):
    class Meta:
        ordering = ('data', )
        verbose_name = 'Venda'
        verbose_name_plural = 'Vendas'

    STATUS_CHOICES = (
        ('a', 'Aprovado'),
        ('e', 'Esperando'),
        ('r', 'Reprovado'),
    )

    FORMA_PAGAMENTO_CHOICES = (
        ('b', 'Boleto'),
        ('c', 'Cartão'),
    )

    produto = models.ForeignKey(Produto, on_delete=models.PROTECT)
    comprador = models.ForeignKey(User, on_delete=models.PROTECT)
    data = models.DateTimeField(u'Data', auto_now_add=True)
    valor = models.DecimalField(u'Valor', max_digits=10, decimal_places=2)
    quantidade = models.PositiveIntegerField(u'Quantidade')
    forma_pagamento = models.CharField(u'Forma de Pagamento', max_length=1, choices=FORMA_PAGAMENTO_CHOICES)
    status = models.CharField(u'Status', max_length=1, choices=STATUS_CHOICES)

    def __str__(self):
        return "%s comprou %s" %(self.comprador, self.produto)

class ProdutoImagem(models.Model):

    class Meta:
        verbose_name = 'Imagem'
        verbose_name_plural = 'Imagens'

    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    imagem = models.ImageField(u'Imagem', upload_to='produtos')
    ordem = models.PositiveIntegerField(u'Ordem')

    def __str__(self):
        return "%s" % self.produto

@receiver(post_delete, sender=ProdutoImagem)
def produtoimagem_imagem_post_delete(sender, instance, *args, **kwargs):
    try: instance.imagem.delete()
    except: pass

core/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Venda, Produto

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', )

    new_password = forms.CharField(label='Digite a senha', widget=forms.PasswordInput())
    new_password2 = forms.CharField(label='Digita a senha novamente', widget=forms.PasswordInput())

    def clean_new_password2(self):
        new_password = self.cleaned_data.get('new_password')
        new_password2 = self.cleaned_data.get('new_password2')
        if new_password != new_password2:
            raise forms.ValidationError(u'As duas senhas devem ser iguais.')
        return new_password2

    def save(self, commit=True):
        self.instance.set_password(self.cleaned_data.get('new_password'))
        return super(UserForm, self).save(commit=commit)

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', )

    new_password = forms.CharField(label='Digite a senha', required=False, widget=forms.PasswordInput())
    new_password2 = forms.CharField(label='Digita a senha novamente', required=False, widget=forms.PasswordInput())

    def clean_new_password2(self):
        new_password = self.cleaned_data.get('new_password')
        new_password2 = self.cleaned_data.get('new_password2')
        if new_password or new_password2 and new_password != new_password2:
            raise forms.ValidationError(u'As duas senhas devem ser iguais.')
        return new_password2

    def save(self, commit=True):
        if self.cleaned_data.get('new_password'):
            self.instance.set_password(self.cleaned_data.get('new_password'))
        return super(UserUpdateForm, self).save(commit=commit)

class CompraForm(forms.ModelForm):
    class Meta:
        model = Venda
        fields = ('quantidade', )

    forma_pagamento = forms.ChoiceField(label='Forma de Pagamento', widget=forms.RadioSelect, choices=Venda.FORMA_PAGAMENTO_CHOICES)

    def save(self, compra_view, commit=True):
        venda = self.instance
        venda.forma_pagamento = self.cleaned_data.get('forma_pagamento')
        venda.status = 'a'
        produto = Produto.objects.get(slug=compra_view.kwargs.get('slug'))
        produto.quantidade -= 1
        venda.produto = produto
        venda.comprador = compra_view.request.user
        venda.valor = produto.valor * int(venda.quantidade)
        return super(CompraForm, self).save(commit=commit)

core/views.py
from django.views.generic import (
    TemplateView, DetailView, FormView, ListView,
    UpdateView
)
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User
from django.urls import reverse

from .models import Categoria, Produto, Venda
from .forms import UserForm, UserUpdateForm, CompraForm

class IndexView(ListView):
    template_name = "index.html"
    template_name_ajax = "ajax/produtos.html"
    queryset = Produto.objects.filter(status='P')
    paginate_by = 9

    def get_template_names(self):
        if self.request.is_ajax():
            return [self.template_name_ajax]
        return [self.template_name]

class CategoriaView(ListView):
    template_name = 'categoria.html'
    template_name_ajax = "ajax/produtos.html"
    paginate_by = 9

    def get_template_names(self):
        if self.request.is_ajax():
            return [self.template_name_ajax]
        return [self.template_name]

    def get_object(self):
        return get_object_or_404(Categoria, slug=self.kwargs.get('slug'))

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.produto_set.filter(status='P')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = self.object
        return context

class ProdutoView(DetailView):
    model = Produto
    queryset = Produto.objects.filter(status='P')
    template_name = 'produto.html'

class UserComprasView(DetailView):
    model = User
    template_name = 'user_compras.html'

    def get_context_data(self, **kwargs):
        context = super(UserComprasView, self).get_context_data(**kwargs)
        context['compras'] = Venda.objects.filter(comprador=self.request.user)
        return context

class CadastroView(FormView):
    template_name = 'cadastro.html'
    form_class = UserForm

    def form_valid(self, form):
        user = form.save()
        auth_login(self.request, user)
        return redirect('index')

class CompraView(FormView):
    template_name = 'compra.html'
    form_class = CompraForm

    def get_context_data(self, **kwargs):
        context = super(CompraView, self).get_context_data(**kwargs)
        context['produto'] = Produto.objects.get(slug=self.kwargs.get('slug'))
        return context

    def form_valid(self, form):
        try:
            form.save(compra_view=self)
            return redirect(reverse('user_compras', kwargs={'pk': self.request.user.pk}))
        except Exception:
            return redirect('login')

class UpdateUserView(UpdateView):
    template_name = 'update_user.html'
    form_class = UserUpdateForm

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        user = form.save()
        auth_login(self.request, user)
        return redirect('index')

core/templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-br" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}
  </head>
  <body>
    <header>
      {% block header %}
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-3 offset-md-1 py-4">
              <h4 class="text-white">Categorias</h4>
              <ul class="list-unstyled">
                {% for categoria in categorias %}
                  <li><a href="{{ categoria.get_absolute_url }}" class="text-white">{{ categoria }}</a></li>
                {% endfor %}
              </ul>
            </div>
            <div class="col-sm-2 offset-md-5 py-4">
              {% if user.is_authenticated %}
              <a href="/{{ user.pk }}/user/compras" class="text-white" style="text-decoration: none"><h4 class="text-white">Suas Compras</h4></a>
              {% endif %}
              <a href="{% url 'cadastro' %}" class="text-white" style="text-decoration: none"><h4 class="text-white">Cadastro</h4></a>
              <a href="{% url 'login' %}" class="text-white" style="text-decoration: none"><h4 class="text-white">Login</h4></a>
              <a href="{% url 'logout' %}" class="text-white" style="text-decoration: none"><h4 class="text-white">Logout</h4></a>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="/" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Loja</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
      {% endblock %}
    </header>
    <main role="main">
      {% if user.is_authenticated %}
        <div style="color: #343a40; text-align: right; padding: 20px; padding-bottom: 0px">
          <!--<strong>Bem vindo, {% firstof user.fist_name user.username %}</strong>-->
          <a href="{% url 'update_user' %}" class="text-blue" <strong> Bem Vindo, {% firstof user.fist_name user.username %}</strong></a>
        </div>
      {% endif %}

      {% block main %}
      {% endblock %}

    </main>
    <footer class="text-muted">
      {% block footer %}
      <div class="container text-center">
        <p>&copy; {% now "Y" %}</p>
      </div>
      {% endblock %}
    </footer>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    {% block js %}{% endblock %}
  </body>
</html>

core/templates/cadastro.html
{% extends "base.html" %}

{% block title %}Cadastro - Loja{% endblock %}

{% block main %}
<section class="text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Cadastro</h1>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.name }}_id">{{ field.label }}</label>
                    <input type="{{ field.field.widget.input_type }}" class="form-control{% if field.errors %} is-invalid{% endif %}" id="{{ field.name }}_id" name="{{ field.name }}" {% if field.value %}value="{{ field.value }}"{% endif %}>
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text}}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
    </div>
</div>
{% endblock %}

core/templates/categoria.html
{% extends "base.html" %}
{% load thumbnail static %}

{% block title %}{{ object }} - Loja{% endblock %}

{% block main %}

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ object }}</h1>
        {% comment %}
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
            <a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
        {% endcomment %}
    </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row ajax-pagination" data-page='1' data-max_page="{{ paginator.num_pages }}" data-block='0'>
      {% for produto in object_list %}
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{% thumbnail produto.imagem 525x0 upscale %}" alt="Card image cap">
            <div class="card-body">
                <p><strong class="card-text">{{ produto.nome }} </strong></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{{ produto.get_absolute_url }}"><button type="button" class="btn btn-sm btn-outline-secondary">Comprar</button></a>
                </div>
                <h3> <strong class="card-text">R$ {{ produto.valor }}</strong></h3>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}


{% block js %}
  <script src="{% static 'js/ajax-pagination.js' %}"></script>
{% endblock %}

core/templates/compra.html
{% extends "base.html" %}
{% load thumbnail %}

{% block main %}

<div class="album py-5 bg-light">
    <div class="container">
    	<div class="row">
		    <div class="col-md-4 py-4">
		        <div class="card mb-6 box-shadow">
		          <img class="card-img-top" src="{% thumbnail produto.imagem 525x0 upscale %}" alt="Card image cap">
		        </div>
		    </div>
		    <div class="col-md-3 py-4">
		        <div class="card mb-6 box-shadow">
		          <div class="card-body">
		            <p class="card-text">{{ produto.nome }}</p>
		            <div class="d-flex justify-content-between align-items-center">
		              <small class="text-muted">R$ {{ produto.valor }}</small>
		            </div>
		          </div>
		        </div>
		        <div class="card mb-6 box-shadow">
		          <div class="card-body">
		            <p class="card-text">Descrição</p>
		            <p class="card-text">{{ produto.descricao }}</p>
		          </div>
		        </div>
		    </div>
		    <div class="col-md-2 py-4">
		    	
		    </div>
		    <div class="col-md-2 py-2">
	    		<h1>Comprar</h1>
				<form action="" method="POST">
		            {% csrf_token %}
	                {{ form }}
		            <button type="submit" class="btn btn-primary">Comprar</button>
		        </form>
		    </div>
    	</div>
    </div>
</div>

{% endblock %}

core/templates/index.html
{% extends "base.html" %}
{% load thumbnail static %}

{% block title %}Loja{% endblock %}

{% block main %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row ajax-pagination" data-page='1' data-max_page="{{ paginator.num_pages }}" data-block='0'>
      {% for produto in object_list %}
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="{% thumbnail produto.imagem 525x0 crop %}" alt="Card image cap">
            <div class="card-body">
              <p><strong class="card-text">{{ produto.nome }}</strong></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{{ produto.get_absolute_url }}"><button type="button" class="btn btn-sm btn-outline-secondary">Ver detalhes</button></a>
                </div>
                <strong class="card-text">R$ {{ produto.valor }}</strong>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
  <script src="{% static 'js/ajax-pagination.js' %}"></script>
{% endblock %}

core/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block main %}

<section class="text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Login</h1>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container-fluid">
        <section class="text-center">
            <div class="row">
                <div class="col-md-5">
                    
                </div>
                <div class="col-md-2">
                    {% if not user.is_authenticated %}
                        <p style="color: green">Por favor efetue o login!</p>
                    {% endif %}
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form }}
                            {% for error in form.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary">Logar</button>
                    </form>
                </div>
                <div class="col-md-5">
                    
                </div>
            </div>
        </section>
    </div>
</div>

{% endblock %}

core/templates/produto.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ object }} - Loja{% endblock %}

{% block main %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card mb-6 box-shadow">
          <img class="card-img-top" src="{% thumbnail produto.imagem 525x0 upscale %}" alt="Card image cap">
        </div>
      </div>
      <div class="col-md-6">
        <div class="card mb-6 box-shadow">
          <div class="card-body">
            <p><strong class="card-text">{{ object.nome }}</strong></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% if user.is_authenticated %}comprar{% else %} {% url 'login' %} {% endif %}"><button type="button" class="btn btn-sm btn-outline-secondary">Comprar</button></a>
              </div>
              <h2><strong class="card-text">R$ {{ object.valor }}</strong></h2>
            </div>
          </div>
        </div>
        <div class="card mb-6 box-shadow">
          <div class="card-body">
            <p class="card-text">Descrição</p>
            <p class="card-text">{{ object.descricao }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/update_user.html
{% extends "base.html" %}

{% block title %}Edição de Dados de Usuário{% endblock %}

{% block main %}
<section class="text-center">
    <div class="container">
        <h1 class="jumbotron-heading"> Edição de Dados de  {{ user.username }} </h1>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.name }}_id">{{ field.label }}</label>
                    <input type="{{ field.field.widget.input_type }}" class="form-control{% if field.errors %} is-invalid{% endif %}" id="{{ field.name }}_id" name="{{ field.name }}" {% if field.value %}value="{{ field.value }}"{% endif %}>
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text}}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Editar</button>
        </form>
    </div>
</div>
{% endblock %}

core/templates/user_compras.html
{% extends "base.html" %}

{% block title %}{{ user.username }}{% endblock %}

{% block main %}

<div class="album py-5 bg-light">
    <div class="container-flui">
	    <h1>{{ user.username }}</h1>
	    {% if compras %}
		    <section class="text-center">
			    <table class="table">
					<thead class="thead-dark">
				    	<tr>
				      		<th scope="col">#</th>
				      		<th scope="col">Produto</th>
				      		<th scope="col">Valor</th>
				      		<th scope="col">Quantidade</th>
				      		<th scope="col">Forma de Pagamento</th>
				      		<th scope="col">Data</th>
				      		<th scope="col">Status</th>
				      		<th scope="col">Total</th>
				    	</tr>
					</thead>
					<tbody>
						{% for compra in compras %}
						    <tr>
						      	<th scope="row">{{ forloop.counter }}</th>
						      	<th><a href="{{ compra.produto.get_absolute_url }}">{{ compra.produto }}</a></th>
						    	<th>{{ compra.produto.valor }} R$</th>
						    	<td>{{ compra.quantidade}}</td>
						    	<th>{{ compra.get_forma_pagamento_display }}</th>
						    	<th>{{ compra.data }}</th>
						    	<th>{{ compra.get_status_display }}</th>
						    	<th>{{ compra.valor }} R$</th>
						    </tr>
						{% endfor %}
					</tbody>
				</table>
			</section>
		{% else %}
			<h2>Nenhuma compra realizada!</h2>
		{% endif %}
    </div>
</div>

{% endblock %}